### ISSUE TITLE
Handle (don't log) exception on unknown command/argument

### ISSUE THREAD

**Issue by mishak87** [Kdyby/Console#15]
```
> bin o:su --force
There are no commands defined in the "o:su" namespace.

  Did you mean one of these?
      orm:generate
      orm:clear-cache
      orm
      orm:schema-tool



  (Tracy output was stored in exception-2014-05-13-07-58-20-2d1c81e8f09cc64beeb6389404440c66.html)
```

Should show only the message and return code for unknown command. IMO Tracy is not supposed to log error produced by use mistake.

**Comment by fprochazka** [comment]
I believe this has been already implement, but we've forgotten to close this issue. https://github.com/Kdyby/Console/commit/77a8285aa42f5c6555cf2ed3bb116a10f243ab88

![snimek obrazovky porizeny 2015-06-14 18 07 35](https://cloud.githubusercontent.com/assets/158625/8149352/6665307c-12c0-11e5-9306-3c231d0125a2.png)
