### ISSUE TITLE
Deprecated exceptions

### ISSUE THREAD

**Issue by peterzadori** [Kdyby/Console#25]
Hello.

First of all, let me say thank you for this amazing component! It used to work without any problems, but now after I do clean composer install with "kdyby/console": "2.3.*@dev" in composer.json I get deprecated exceptions like this one when I try to run console:

```
exception 'ErrorException' with message '"
Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0.
Use "Symfony\Component\Console\Helper\QuestionHelper" instead.'
in C:\dev\www\tome\vendor\symfony\console\Symfony\Component\Console\Helper\DialogHelper.php:34
```

**Comment by fprochazka** [comment]
I see. The question helper should be added, but the dialog helper should not be removed yet. Can you send a pullrequest please?

**Comment by fprochazka** [comment]
Fixed, thank you for reporting
