### ISSUE TITLE
Error handling - wrong router

### ISSUE THREAD

**Issue by besir** [Kdyby/Console#27]
Hi, I found this potentialy problem.

If I have router e.g.

```php
<?php
class RouterFactory
{
	public function createRouter()
	{
		$privateRouter = new RouteList('Private');

		$privateRouter[] = new Route('<module>/<presenter>[/<action>][/<id>]',
				array(
					'module' => 'Dashboard',
					'presenter' => 'Dashboard',
					'action' => 'default',
				));
		return $privateRouter;
	}
}
```

Console return error like 
**[Nette\Application\BadRequestException]**
Cannot load presenter 'Private:Kdyby:Cli', class 'App\PrivateModule\KdybyModule\Presenter\CliPresenter' was not found in '/home/vagrant/sources/personal/baria/baria    _crm/app/core/PrivateModule/KdybyModule/presenters/CliPresenter.php'.

Solution:

Creating RouteList without module specification and insert Concrete module RouteList to them.

```php
<?php
class RouterFactory
{
	public function createRouter()
	{
		$router = new RouteList();
		$privateRouter = new RouteList('Private');

		$privateRouter[] = new Route('<module>/<presenter>[/<action>][/<id>]',
				array(
					'module' => 'Dashboard',
					'presenter' => 'Dashboard',
					'action' => 'default',
				));

		$router[] = $privateRouter;
		return $privateRouter;
	}
}
```

**Comment by fprochazka** [comment]
Thank you for reporting, I believe this solves it.
