### ISSUE TITLE
Drop dependency on Nette\Application

### ISSUE THREAD

**Issue by JanTvrdik** [Kdyby/Console#30]
I don't understand why does console need to depend on Nette\Application so I'd like to propose to relax this dependency.

To make it a bit clearer. I'd like to do this:

~~~php
$dic = require __DIR__ . '/../app/bootstrap.php';
$app = $dic->getByType(Kdyby\Console\Application::class);
$app->run();
~~~

**Comment by enumag** [comment]
:+1: I also use `Kdyby\Console\Application` directly. For links generation in commands it's better to use nextras/link-factory.

**Comment by fprochazka** [comment]
You should be able to do the thing that you're suggesting right now, it should work without any problems.

But, it is there for two reasons... 

1) simplicity - you install the extension run `php www/index.php` and it just works™
2) "fixed" links generation

The second one is not relevant in Nette 2.3, so this could be refactored a bit.

**Comment by JanTvrdik** [comment]
> it should work without any problems.

It does not work because `ConsoleExtension` assumes that services such as `application` do exist. The simple solution may be to use `hasDefinition` before `getDefinition`.

**Comment by fprochazka** [comment]
I'm on board with that. Making it optional makes sense :)

**Comment by TomasVotruba** [comment]
:+1:

**Comment by vojtech-dobes** [comment]
:+1:
