### ISSUE TITLE
Missed dependency on Nette\Nette

### ISSUE THREAD

**Issue by zeleznypa** [Kdyby/Console#32]
In the Constructor is dependency on class constants:
https://github.com/Kdyby/Console/blob/master/src/Kdyby/Console/Application.php#L45

But there are not present in depended nette components

**Comment by vojtech-dobes** [comment]
Better to not make it dependency and handle it extension, that would be my guess :).

**Comment by zeleznypa** [comment]
Better will be remove dependency on that constants :)

**Comment by fprochazka** [comment]
Thank you for reporting. It should be fixed now, right?

**Comment by zeleznypa** [comment]
Thanks :+1:
