### ISSUE TITLE
Compatibility with Symfony/Console 2.6

### ISSUE THREAD

**Issue by petrnemec** [Kdyby/Console#35]
Kdyby/Console 2.4.0 and 2.3.2 is not compatible with Symfony/Console 2.6.x

````
Service 'console.helperSet': Unable to pass arguments, class Symfony\Component\Console\Helper\ProgressHelper has no constructor.
````

````
Service 'console.helperSet': Unable to pass arguments, class Symfony\Component\Console\Helper\DialogHelper has no constructor.
````

**Comment by fprochazka** [comment]
Try dev-master please.

**Comment by petrnemec** [comment]
kdyby/console dev-master requires symfony/console >= 2.7

**Comment by fprochazka** [comment]
This should be fixed now, if current master still doesn't work for you, please reopen this issue. Thank you for reporting.
