### ISSUE TITLE
LogicException  An option named "debug-mode" already exists.

### ISSUE THREAD

**Issue by Lexinek** [Kdyby/Console#36]
5514de56b72a1d654458846bdacaefd8b4a0ced7 causing LogicException when running
```
sudo php www/index.php orm:schema-tool:update --force --dump-sql
```

**Comment by Daaarkling** [comment]
same issue in ~2.3 but works in @dev version.

**Comment by fprochazka** [comment]
If you're using dev version of kdyby/doctrine, use also dev version of kdyby console :)

**Comment by j0hny666** [comment]
confirming in 2.3

**Comment by fprochazka** [comment]
The 3.0 has been tagged, please use that.
