### ISSUE TITLE
Dvě aplikace s jedním vendor

### ISSUE THREAD

**Issue by h4kuna** [Kdyby/Console#39]
Ahoj,
mám use case se kterým se chci podělit.

Máme aplikaci kde je stará část a nová. Stará jede a nová se vyvíjí obě mají společný vendor. Na nové verzi využíváme kdyby\console a na staré ji nechceme takže není ani definovaný extension v neonu. Jenže nette 2.3 jak si hledá presentery, aby je uložil do Containeru a připravil je jako služby, tak stará aplikace přestala chodit, protože nette našlo KdybyModule\CliPresenter a to má závislosti na Kdyby\Application. Dohledal jsem že to jde vypnout

```
application:
    scanComposer: false
```

V tuto chvíli je to takto dostačující, ale připravili jsme se o možnost načítat presentery přes composer, což zatím nepoužíváme ani na jedné verzi.

**Comment by fprochazka** [comment]
Hmm, to moc nevím jak řešit.

**Comment by h4kuna** [comment]
Ano to je velký problém, protože je na www/index.php navázaný CliRouter a když extension zaregistruju tak nám přestanou fungovat naše scripty závislý pro build. Takže jedině všechno přepsat do kdyby\console. Je mi šlo o to aby bylo známé to že když stáhneš doplněk a nezapíšeš v neonu zaregistrování extension tak stejně vyžaduje závislosti. Což není úplně optimální ale taky nemám návrh jak to vyřešit. Krom toho nastavení pro application.

**Comment by fprochazka** [comment]
A zkoušel jsi 

```php
console:
    disable: true
```

**Comment by h4kuna** [comment]
Nezkoušel neznám :)

**Comment by h4kuna** [comment]
Vyzkoušel jsem, řekl bych že to nefunguje.
Cannot load presenter 'Kdyby:Cli', class '\App\Modules\Kdyby\CliPresenter' was not found. 

By neměl mít důvod tím pádem hledat pomocí routru CliPresenter. Až ale toto vyřeším tak pak to nevyřeší to že nette automaticky najde CliPresenter a bude se snažit do nej naroubovat závislosti přes konstruktor a inject*.

**Comment by fprochazka** [comment]
CliPresenter [vyžaduje pouze Console\Application](https://github.com/Kdyby/Console/blob/master/src/Kdyby/Console/CliPresenter.php#L42), tzn že registrací extension by ta služba měla vzniknout a tím že ji řekneš `disable: true` by neměla registrovat router ani se bindovat na `Nette\Application`, tim padem by to mělo fungovat.

**Comment by fprochazka** [comment]
Pokud předchozí rada nepomohla, řešením by mělo být zaregistrovat si `KdybyModule\CliPresenter` jako službu a vypnout u něj DI injects (tedy automatické injectování do `inject*()` metod). V následující major verzí půjde `CliPresenter` úplně pryč.
