### ISSUE TITLE
Add CoC Document

### ISSUE THREAD

**Issue by Northys** [Kdyby/Console#47]

**Comment by matej21** [comment]
![](http://memecrunch.com/meme/ASSSM/here-is-your/image.gif?w=499&c=1)

**Comment by fprochazka** [comment]
![taser you](https://cloud.githubusercontent.com/assets/158625/12536230/a7105fea-c29f-11e5-929c-4c04c3c59c0c.gif)

**Comment by fprochazka** [comment]
:heart:
