### ISSUE TITLE
Shouldn't we run the Nette\Application\Application onShutdown event?

### ISSUE THREAD

**Issue by Fuco1** [Kdyby/Console#59]
`onStartup` is called because so far the control wasn't handled over to `Kdyby\Console\Application`, but the original `onShutdown` is ignored (you call `onError` however).

If this is undesirable, maybe a way to attach console-only shutdown event would be helpful.

My usecase right now is: I use `symfony/process` to start some background processes, but when the main process dies it kills the children (standard unix behaviour).  So on the shutdown hook I want to wait for the child processes to finish, then really terminate.  I want to wait up in both web request and console request, so for me a common handler is fine (plus you can always test there if you run in the cli)

**Comment by Fuco1** [comment]
You're right about my problem, though we're dealing with such a mad architecture (legacy yay) this was the simplest way to get it going, which lead to discovering of this issue.  Everything calls everything and we have quite literally no idea where the processes are forked/started ~_~.

Anyway, thanks for looking into this!

**Comment by fprochazka** [comment]
@Fuco1 Thank you for reporting this!

**Comment by Fuco1** [comment]
@fprochazka Unfortunatelly I no longer work at the company so I can't test this :/  I'll notify my colleague so maybe they will take a look at it.

**Comment by fprochazka** [comment]
@Fuco1 Thank you!
