### ISSUE TITLE
Check argv before constructing ArgvInput

### ISSUE THREAD

**Issue by northys** [Kdyby/Console#63]

**Comment by fprochazka** [comment]
What is the use-case? Aren't you somehow modifying the `$_SERVER` ?

**Comment by fprochazka** [comment]
I don't remeber what this was about. If it's still a problem, please let me know.

**Comment by northys** [comment]
the arachne/codeception module did, but nette checks it so i dont see any reason why you wouldnt do that

**Comment by northys** [comment]
ping @fprochazka

**Comment by fprochazka** [comment]
Okey

**Comment by fprochazka** [comment]
@northys Thanks!
