### ISSUE TITLE
Argument 1 passed to Symfony\Component\Console\Application::renderException() must be an instance of Exception, instance of TypeError given

### ISSUE THREAD

**Issue by Lexinek** [Kdyby/Console#64]
Is this issue of Symfony/Console or Kdyby/Console?

Since `Symfony\Component\Console\Application::renderException(\Exception $e, OutputInterface $output)` is excepting type of `\Exception` type errors should not be sent to it.

Problem is in `Kdyby\Console\Application::handleException()` where `renderException()` is called.

Any ideas how to fix this?

Anyways type error causing the exception is:
`Argument 1 passed to Zenify\DoctrineMigrations\EventSubscriber\ChangeCodingStandardEventSubscriber::getMigrationFileByVersion() must be of the type st ...`

**Comment by kerleba** [comment]
This issue is already fixed in master. See #61

**Comment by Lexinek** [comment]
Thank you for info @kerleba i will update my composer.json, but as we prefer to use stable versions it would be nice if it could get tagged @fprochazka

**Comment by fprochazka** [comment]
Closing as it's already fixed.
