### ISSUE TITLE
Bad absolute path when not in a domain root

### ISSUE THREAD

**Issue by dakur** [Kdyby/Console#67]
When I set up in config:
```
console:
    url: http://domain.tld/path
```
and then use `Nette\Application\LinkGenerator` or `Nextras\Application\LinkFactory` in a command:
```
$this->linkFactory->link('Presenter:method', ['code' => $code]);
```
it returns me `http://domain.tld/ABCDEF` instead of `http://domain.tld/path/ABCDEF`.

**Comment by dakur** [comment]
I forgot the version numbers:
- nette/application: 2.3.13
- kdyby/console: 2.6.1

**Comment by fprochazka** [comment]
Hi, thanks for reporting this. Tbh, I don't think the extension should try to autodetect this. But I'll add a configuration option for it.
