### ISSUE TITLE
%wwwDir% 

### ISSUE THREAD

**Issue by pitr82** [Kdyby/Console#69]
Ahoj, 
používám rozšíření webloader, kde načítám soubory pomocí %wwwDir% (/www/mujprojekt)
,ale když chci spustit: php bin/console command 
tak mi to padne na chybě, že neumí najít soubory, protože v tomhle kontextu je %wwwDir%  - /www/mujprojekt/bin

**Comment by fprochazka** [comment]
Ahoj, `wwwDir` [můžeš nastavit](https://github.com/nette/sandbox/blob/f2acaa7cb28d3768aeb43fe4730838738f733d4e/app/bootstrap.php#L7) jako parametr

```php
$configurator->addParameters([
    'appDir' => __DIR__,
    'wwwDir' => dirname(__DIR__) . '/www',
]);
```
