### ISSUE TITLE
[Semantical Error] The annotation "@phpcsSuppress" in class KdybyModule\CliPresenter was never imported. 

### ISSUE THREAD

**Issue by BigOHenry** [Kdyby/Console#75]
`[Semantical Error] The annotation "@phpcsSuppress" in class KdybyModule\CliPresenter was never imported. Did you maybe forget to add a "use" statement for this annotation?`

When i delete the anotation from `CliPresenter` it works fine

```
/**
 * @phpcsSuppress KdybyCodingStandard.Files.TypeNameMatchesFileName
 */
class CliPresenter extends \Nette\Application\UI\Presenter
```

**Comment by enumag** [comment]
No fix needed. Either setup your Kdyby/Annotations correctly to ignore this annotation or even better don't use CliPresenter. I think we should mark it as deprecated since there is no reason to use it anymore.

**Comment by BigOHenry** [comment]
How can i set it pls? I am just using Kdyby/RabbitMq with Kdyby/Console...

**Comment by BigOHenry** [comment]
ah, the problem is in Ublaboo/ApiRouter:
![2018-04-12 17_40_12-debian-test - vmware workstation 14 player non-commercial use only](https://user-images.githubusercontent.com/15823552/38688206-d7e65d48-3e78-11e8-920d-3960bc2088d1.png)

**Comment by enumag** [comment]
Add the annotation to ignore as I said above. https://github.com/Kdyby/Annotations/blob/master/docs/en/index.md#configuration
