### ISSUE TITLE
CliRouter is child of CliRouter is child of ...

### ISSUE THREAD

**Issue by MilanPala** [Kdyby/Console#84]
![image](https://user-images.githubusercontent.com/1717814/64860623-00b1c200-d62e-11e9-9fbd-66deddca67b5.png)

**Comment by slepic** [comment]
I've got the same problem.
I would redefine the problem not CliRouter child of CliRouter, etc.
But rather RouteList child of RouteList, etc...

Ive narrowed the problem to this line:
https://github.com/Kdyby/Console/blob/master/src/DI/ConsoleExtension.php#L218

Where the console extension picks the default routelist and replaces it with new one, but at the same time it appends the routelist to itself.

This causes the router to enter infinite loop.

**Comment by slepic** [comment]
#85 fixes the problem and even reverts BC break where console.originalRouter service was made no longer available
https://github.com/Kdyby/Console/blob/v2.7.1/src/DI/ConsoleExtension.php#L206

**Comment by VBoss** [comment]
This issue is resolved by this PR https://github.com/Kdyby/Console/pull/85 @MilanPala reported this was working fix.
Thank you 👍
